config/routes.rb
Rails.application.routes.draw do
  root to: "main#home"
  get '/', to: 'main#home'

  get '/ebooks/:id', to: 'ebooks#ebooks'
  get '/download/:id', to: 'ebooks#download', as: 'download'

  get '/cart', to: 'cart#cart'
  post '/cart', to: 'cart#add_to_cart'
  delete '/cart', to: 'cart#remove_from_cart'

  get '/order/checkout', to: 'order#order_confirm'
  post '/order/notify', to: 'order#notify'
  get '/order/notify', to: 'order#mail_last_order'
  get '/order/create', to: 'order#create_payment'
  get '/order/confirmation', to: 'order#confirmation'

  get '/orders', to: 'user#orders'

  #get 'main/contact'
  #get '/about', to: 'main#about'

  devise_for :users

  devise_for :managers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/managers', to: redirect('/admin')

  mount ActionCable.server => '/cable'

end

app/models/order.rb
class Order < ApplicationRecord
  before_update :check_payment
  has_many :ebooks, through: :ebook_orders
  has_many :ebook_orders
  belongs_to :user

  private
    def check_payment
      logger.info "mudando " + self.paid_was.to_s
      logger.info "para " + self.paid.to_s
      if self.paid != self.paid_was
        ActionCable.server.broadcast "orders_#{self.user_id}",
            id: self.id.to_s,
            content: OrderController.new.render_to_string(self)
        UserMailer.ebooks_download(self).deliver_now if self.paid
      end
      return true
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  include Concurrent::Async
  before_action :authenticate_user!, except: :notify

  def order_confirm
    session[:redirect_url] = nil
    if session[:cart].nil? || session[:cart].empty?
      redirect_to root_url
    else
      ebooks_in_cart
    end
  end

  def ebooks_in_cart
    @ebooks = []
    @cart_total = 0.0
    @removed = [];

    ebook_list = session[:cart];
    ebook_list.each do |e|
      ebook = Ebook.find(e)
      if current_user.has_ebook?(e)
        @removed << ebook
      else
        @ebooks << ebook
        @cart_total += ebook.price
      end
    end
    @removed.each {|r|
      session[:cart] = ebook_list.delete r.id }
  end

  def create_payment
    if !session[:redirect_url].nil?
      redirect_to session[:redirect_url]
      session[:redirect_url] = nil
      return
    end

    ebooks_in_cart

    order = current_user.orders.create(total: @cart_total, paid: false)
    payment = PagSeguro::PaymentRequest.new

    payment.reference = order.id
    payment.notification_url = order_notify_url #"https://5c478c65.ngrok.io/order/notify"
    payment.redirect_url = order_confirmation_url #"https://5c478c65.ngrok.io/order/confirmation"

    @ebooks.each do |e|
      order.ebook_orders.create(value: e.price, ebook: e)
      payment.items << {
        id: e.id,
        description: e.title,
        amount: e.price,
        weight: 0
      }
    end

    response = payment.register

    if response.errors.any?
      order.destroy
      raise response.errors.join("\n")
    else
      session[:redirect_url] = response.url
      redirect_to response.url
      session[:cart] = []
      return
    end
  end

  skip_before_action :verify_authenticity_token, only: :notify
  def notify
    async.process_payment params[:notificationCode]

    render body: nil, status: 200
  end

  def mail_last_order
    order = Order.last
    UserMailer.ebooks_download(order.user, order).deliver_now
    redirect_to root_url
  end

  def process_payment(token)
    transaction = PagSeguro::Transaction.find_by_notification_code(token)

    if transaction.errors.empty?
      order = Order.find(transaction.reference)
      order.update_attribute(:paid, true) if transaction.status.id == "3" # pago
      UserMailer.ebooks_download(order.user, order).deliver_now
    end
  end

end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/order/order_confirm.html.erb
<% provide(:head_title, 'Checkout') %>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="page-header center-text">
        <% if @removed.count > 0 %>
        <h1>Você já possui estes ebooks, eles serão removidos do carrinho:</h1>
      </div>
          <% @removed.each do |r| %>
          <p class="alert alert-danger"><%=r.title%></p>
          <% end %>
          <div class="pull-right">
            <p><a href="<%=order_checkout_url%>" class="btn btn-default background-green">Prosseguir</a></p>
          </div>
        <% else %>
        <h1>Seu pedido</h1>
      </div>

      <table class="table table-cart">
        <thead>
          <th>Titulo</th>
          <th>Preço</th>
        </thead>
        <tbody>
          <% @ebooks.each do |e| %>
          <tr>
            <td>
              <a href="<%="/ebooks/#{e.id}"%>">
                <%=e.title%></td>
              </a>
            <td class="cart-price-size"><%= number_to_currency_br e.price %></td>
          </tr>
          <% end %>
          <tfoot>
            <td>Total:</td>
            <td><%= number_to_currency_br @cart_total %></td>
          </tfoot>
        </tbody>
      </table>
      <div class="pull-right">
        <p><a href="<%=order_create_url%>" class="btn btn-default background-green">Pagar com PagSeguro</a></p>
        <p>...ou <a href="<%=root_url%>">continuar comprando</a> </p>
      </div>
      <% end %>
    </div>
  </div><!-- end .row -->
</div><!-- end .container-fluid -->