config/routes.rb
Rails.application.routes.draw do
  root to: "main#home"
  get '/', to: 'main#home'

  get '/ebooks/:id', to: 'ebooks#ebooks'
  get '/download/:id', to: 'ebooks#download', as: 'download'

  get '/cart', to: 'cart#cart'
  post '/cart', to: 'cart#add_to_cart'
  delete '/cart', to: 'cart#remove_from_cart'

  get '/order/checkout', to: 'order#order_confirm'
  post '/order/notify', to: 'order#notify'
  get '/order/notify', to: 'order#mail_last_order'
  get '/order/create', to: 'order#create_payment'
  get '/order/confirmation', to: 'order#confirmation'

  get '/orders', to: 'user#orders'

  #get 'main/contact'
  #get '/about', to: 'main#about'

  devise_for :users

  devise_for :managers
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/managers', to: redirect('/admin')

  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:head_title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="down-60-px">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href='<%= root_path %>'>OpenEbookCommerce</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <form class="navbar-form navbar-left" action="<%= root_url %>">
            <div class="form-group">
              <select class="form-control" name="c">
                <option value="todos">Todos</option>
                <!-- default -->
                <% all_tags.each do |t| %>
                  <option value='<%= "#{t.name}" %>'
                    <%= "selected='selected'" if t.name.capitalize == category %> ><%= t.name.capitalize %></option>
                <% end %>
              </select>
              <input id='search_by_keyword' type="text" class="form-control" placeholder="Procurar" name="s">
            </div>
            <button type="submit" class="btn btn-default">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </button>

            <a href='<%=cart_url%>' class="btn btn-info btn-cart">
              <span class="glyphicon glyphicon-shopping-cart"></span>
              Ir para Carrinho (<%=cart_total%>)
            </a>
          </form>

          <ul class="nav navbar-nav navbar-right ">
            <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<%=orders_url%>">Meus e-books</a>
                </li>
                <li>
                  <a href="<%=edit_user_registration_path%>">Minha conta</a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
                </li>
              </ul>
            </li>
            <% else %>
            <li>
              <a href="<%=new_user_session_path%>">Entrar</a>
            </li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>

    <%= render 'shared/flash_messages' %>
    <%= yield %>
    <!-- <footer class="container-fluid text-center">
      <p>Footer Text</p>
    </footer> -->
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:head_title) + " Conta") %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash_messages' %>
    <div class="container horizontal-centering vertical-centering">
      <div>
         <h3 class="text-center gray-text2"><%= yield :title %></h3>
         <p class="gray-text2"><%= yield :sub_title %></p>
       </div>
      <%= yield %>
    </div>
  </body>
</html>